@echo off
REM ============================================================
REM  SUR - HDRIs Viewer : démarre un serveur HTTP local
REM  Double-clic pour lancer. Le navigateur s'ouvre automatiquement.
REM ============================================================

setlocal
cd /d "%~dp0"

echo.
echo  SUR - HDRIs Viewer - Demarrage du serveur local
echo  ================================================
echo.

REM ============================================================
REM  Generation automatique de config.js
REM  Fichier lu par pathutils.js pour auto-detecter le chemin
REM  absolu du projet (les backslashes Windows sont doubles
REM  pour etre valides en string JS).
REM ============================================================
echo  Generation de config.js avec le chemin du projet :
echo    %CD%
(
echo // Auto-generated by start-server.bat - do not edit manually.
echo // Re-execute start-server.bat to refresh after moving the project.
echo window.__SUR_HDRI_PROJECT_ROOT__ = "%CD:\=\\%";
) > config.js
echo.

REM --- Tentative 1 : python (PATH standard) ---
where python >nul 2>nul
if %errorlevel% == 0 (
    echo  [OK] Python detecte. Demarrage sur http://localhost:8000
    echo.
    start "" "http://localhost:8000"
    python -m http.server 8000
    goto :eof
)

REM --- Tentative 2 : py (launcher Windows) ---
where py >nul 2>nul
if %errorlevel% == 0 (
    echo  [OK] Python launcher (py) detecte. Demarrage sur http://localhost:8000
    echo.
    start "" "http://localhost:8000"
    py -m http.server 8000
    goto :eof
)

REM --- Tentative 3 : node (npx serve) ---
where node >nul 2>nul
if %errorlevel% == 0 (
    echo  [OK] Node.js detecte. Demarrage avec npx serve sur http://localhost:3000
    echo.
    start "" "http://localhost:3000"
    npx --yes serve . -l 3000
    goto :eof
)

REM --- Aucun outil dispo ---
echo  [ERREUR] Ni Python ni Node.js n'est installe sur cette machine.
echo.
echo  Solutions :
echo    1. Installer Python : https://www.python.org/downloads/
echo       (cocher "Add python.exe to PATH" pendant l'install)
echo    2. Installer Node.js : https://nodejs.org/
echo    3. Utiliser l'extension "Live Server" dans VS Code
echo.
pause
