#!/usr/bin/env bash
# ============================================================
#  SUR - HDRIs Viewer
#  Demarre un serveur HTTP local (macOS / Linux)
#
#  Usage :
#    chmod +x start-server.sh    # une seule fois
#    ./start-server.sh
# ============================================================

set -e

cd "$(dirname "$0")"

echo
echo " SUR - HDRIs Viewer - Demarrage du serveur local"
echo " ================================================"
echo

# --- Generation de config.js (chemin absolu auto-detecte) ---
PROJECT_ROOT="$(pwd)"
echo " Generation de config.js avec le chemin du projet :"
echo "   $PROJECT_ROOT"
{
  echo "// Auto-generated by start-server.sh - do not edit manually."
  echo "// Re-execute start-server.sh to refresh after moving the project."
  echo "window.__SUR_HDRI_PROJECT_ROOT__ = \"${PROJECT_ROOT//\\/\\\\}\";"
} > config.js
echo

PORT=8000
URL="http://localhost:$PORT"

open_browser() {
  case "$(uname -s)" in
    Darwin*) open "$URL" ;;
    Linux*)  xdg-open "$URL" >/dev/null 2>&1 || true ;;
  esac
}

# --- Tentative 1 : python3 ---
if command -v python3 >/dev/null 2>&1; then
  echo " [OK] python3 detecte. Demarrage sur $URL"
  echo
  open_browser
  python3 -m http.server "$PORT"
  exit 0
fi

# --- Tentative 2 : python (ancien) ---
if command -v python >/dev/null 2>&1; then
  echo " [OK] python detecte. Demarrage sur $URL"
  echo
  open_browser
  python -m http.server "$PORT"
  exit 0
fi

# --- Tentative 3 : node + npx serve ---
if command -v npx >/dev/null 2>&1; then
  echo " [OK] Node.js detecte. Demarrage avec npx serve sur $URL"
  echo
  open_browser
  npx --yes serve . -l "$PORT"
  exit 0
fi

# --- Aucun outil dispo ---
cat <<EOF
 [ERREUR] Aucun runtime detecte (python3 / python / node).

 Installation :
   - Python 3 : https://www.python.org/downloads/
   - Node.js  : https://nodejs.org/

 Apres install, relance ce script.
EOF
exit 1
